#!/bin/bash

# mkdir ~/.dotfiles
# cd ~/.dotfiles
# git remote add origin git@github.com:natekratchman/dotfiles.git
# git fetch origin
# git merge origin

mv ~/.bash_profile ~/.bash_profile-BACKUP
mv ~/.bashrc ~/.bashrc-BACKUP
mv ~/.vimrc ~/.vimrc-BACKUP
mv ~/.mappings.vim ~/.mappings.vim-BACKUP
mv ~/.tmux.config ~/.tmux.config-BACKUP

touch ~/.bash_profile
touch ~/.bashrc
touch ~/.vimrc
touch ~/.mappings.vim
touch ~/.tmux.config

ln -s ~/.dotfiles/.bash_profile ~/.bash_profile
ln -s ~/.dotfiles/.bashrc ~/.bashrc
ln -s ~/.dotfiles/.vimrc ~/.vimrc
ln -s ~/.dotfiles/.mappings.vim ~/.mappings.vim
ln -s ~/.dotfiles/.tmux.config ~/.tmux.config

